name: aicup-llmrag
dependencies:
    - python=3.8
    - pip
    - pip:
        - pdfplumber
        - tqdm
        - rank_bm25
        - git+https://github.com/APCLab/jieba-tw.git
        - cn2an
        - selenium